# Generated by Django 6.0.2 on 2026-02-18 20:02

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bucket', models.CharField(choices=[('fixed', 'Fixed Costs'), ('investments', 'Investments'), ('savings', 'Savings'), ('guilt_free', 'Guilt-Free Spending')], max_length=20)),
                ('target_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('monthly_cap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for auto-tagging (e.g. "spotify,netflix,hulu")')),
                ('icon', models.CharField(blank=True, default='bi-tag', help_text='Bootstrap icon class', max_length=50)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tracker.household')),
            ],
            options={
                'verbose_name_plural': 'Budget categories',
                'ordering': ['bucket', 'name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='tracker.household')),
                ('linked_category', models.ForeignKey(blank=True, help_text='Link to a savings category to auto-track contributions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_goals', to='tracker.budgetcategory')),
            ],
            options={
                'ordering': ['target_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=7)),
                ('receipt_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.budgetcategory')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_net_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('JPY', 'Japanese Yen (¥)'), ('NZD', 'New Zealand Dollar (NZ$)')], default='USD', max_length=3)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tracker.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investments_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guilt_free_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investments_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guilt_free_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('health_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('savings_rollover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tracker.household')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('household', 'month')},
            },
        ),
    ]
